### ISSUE TITLE
No symbols displayed on MacOS (all browsers)

### ISSUE THREAD

**Issue by sturdysturge** [noahsark769/sfsymbols.com#8]
Chrome, Firefox and Safari on macOS Catalina 10.15.4 display no symbols at all.

**Comment by noahsark769** [comment]
Hey there! As discussed on Twitter, this is actually expected - Apple's licensing for the SF Symbols font disallows usage except in apps. See here for more information: https://noahgilmore.com/blog/taking-down-sfsymbols/
